### ISSUE TITLE
Modal oscillator: no sound on Prologue 16

### ISSUE THREAD

**Issue by Ema41** [peterall/macro-oscillator2-prologue#2]
Hi Peter,
First: Thanks for implementing mutable osc in Prologue. Amazing job!
I have problem with the modal oscillator: no sound at all.
I tried to send it (alone) from librarian several times to Prologue. It appears in it. I enter parameters as you describe in your  readme tips (no "0" values)... And I still have no sound.
Is it a known issue, or maybe I missed something?
Thanks again for all your works,
Regards,
Mathieu.

**Comment by peterall** [comment]
Hey, thanks for trying it out and I’m sorry it’s not working. Someone on reddit reported the same issue so there’s something going on, but I’ve tried the exact same binary on my prologue and it works fine (worst developer excuse I know - “works on my machine” 😕)

Maybe I can try and replicate your environment more closely; Are you running the librarian on Mac or PC (I’ve only tried on mac)? Which slot are you loading into? Are there other oscillators loaded and if so in which slots? Are you running latest firmware?

Thankful for your help! 😊

**Comment by Ema41** [comment]
Hi Peter,
I'm on mac OS10.10 with the latest firmware in Prologue 16. I've got all your oscillators (plaits), and the wave (native) in first position and the free one from blinds. I've posted in a french musician forum (audiofanzine) to see if other owners had same problem, but no answer until now...
Maybe I should erase all but I already made good sounds with your Plaits osc.
Did you try it on a Prologue 8 or 16?
Thanks again for your kind help,
I hope to find a solution.
Mathieu.

**Comment by Ema41** [comment]
Hi Peter,
There is another user on Audiofanzine that experienced the exact same bug.
We hope you'll find the bug... (Unfortunately, I can't help you: I'm a musician but not a programmer...)
Thanks again!
Mathieu.

**Comment by peterall** [comment]
Hey, sorry about the late reply. I'm running on a Prologue 16 with latest firmware so no differences there. Overall sounds like we have a similar config so hard to track down. One thing is that the random function is initialized with an "MCU specific unique hash" which creates some variability.

I'll make test build and post here soon if you're available to test.

**Comment by peterall** [comment]
Can you try this? I've changed the random initialization and also decreased the number of resonators as I know it's been close to the cpu limit.

[modal_strike_test_1.zip](https://github.com/peterall/eurorack-prologue/files/2906853/modal_strike_test_1.zip)

**Comment by Ema41** [comment]
Hi Peter,
Sorry for the delay. I've just tested it, and no sound again :-(
Thanks again. Hope you'll find it!

**Comment by CL516** [comment]
Hi, I also have no sound for Modal Oscillator on 2 separate Prologue16.  (Had to exchange one due to shipping damage).
I used Korg Librarian on iMac OSX 10.12.6, latest Prologue Firmware (1.3 i think) and did the voice update afterwards as well.  

thanks

**Comment by eriklaurikulo** [comment]
I have no sound on my Minilogue XD either. I can open a new issue case if you'd like.

**Comment by peterall** [comment]
Thanks for trying it out! My prologue is in the shop so not much I can do at the moment but as soon as I get it back I can start looking into it again!

**Comment by peterall** [comment]
Hey Erik! Is this in the modal oscillator or in any oscillator? If none of them are working then if you could please open a new issue I can track that as a separate issue.

**Comment by eriklaurikulo** [comment]
> Hey Erik! Is this in the modal oscillator or in any oscillator? If none of them are working then if you could please open a new issue I can track that as a separate issue.

It's only the Modal one (mod_st) and no matter what settings I have. All other works very well (thank you so much for them!)

EDIT: I am using the latest firmware for the Minilogue XD (1.05).

**Comment by scottjgailey** [comment]
Hey @peterall , same issue with the Modal Strike here. Prologue 49, latest firmware. Thanks for these oscillators!

**Comment by peterall** [comment]
Hey Scott! Thanks for the feedback! As soon as my prologue is back from repairs I’ll get back to troubleshooting (and music making 😄)

**Comment by Sebo1971** [comment]
Hi, I have no sound out of the modal strike either (all other oscillators works well). I have Prologue 8 with latest firmware (1.30) and I'm using the librarian on Windows 10.
Thank you for making this oscillators available!!!

**Comment by Flyweightt** [comment]
Hi Peter,

Thanks a lot for your efford to port the MI OSC's to the prologue!! Awesome ! :)
For me the Prologue 16 and the Modal Strike does not work neither.
I have updated the to the latest firmware and also did the voice update.

https://github.com/korginc/logue-sdk/tree/master/tools/logue-cli

Wondering if the logue-cli will give some usefull debugging info if you use it to load the unit to the Prologue.

**Comment by Flyweightt** [comment]
Update note from Sinevibes from their Korg Tube OSC.
– Removed buffer initialization on plugin startup to avoid possible processor overload or freeze.
– Removed buffer initialization on every keypress to avoid possible processor overload or freeze.

**Comment by NipLars** [comment]
Thanks a lot for providing these oscillators.
Prologue-8 - updated to latest firmware - also no sound on this oscillator.
I set the parameters for sample provided on code page.
I stored a program and parameters go with it - so far so good.
This is the last one currently - only had P8 for two days so far.
Don't know if anything at all regarding that - until I load something after - yours are slot 2-13.
Korg midi drivers has always been flaky - but seems no problems otherwise.
There is a delay changing oscillators - first time over 1s or so from seing name until sounding.

**Comment by cosmospacemonkey** [comment]
Hi peter, thanks for the great OSCs! Quick question: Do I need to update the files I am using? It looks like there is a 1.4 ver. Im using a Minilogue XD. I downloaded the zip from February - I believe 1.3. The only thing is that 1.4 is for prologue. So am I correct in thinking I’m set for now? I noticed a strings file in 1.4. Some advise that the prologue files will work in the XD. Could you clarify anything I may be mistaken about? Thanks!

**Comment by peterall** [comment]
Hey all!

Thanks all for your insights and interest! There's a 1.5 version new built on a newer SDK supporting prologue, minilogue-xd and the nu:tekt NTS-1.

Regarding this issue with `osc_modal_strike`,  it seems like it's been occuring when doing a fresh install of the oscillator - which of course is the standard use-case! When I've been developing I've been doing incremental builds playing around with the implementation on the prologue and this has for some reason been working fine! 

If you guys want to try roughly the same procedure which has worked for me is to install a less CPU heavy version first, moving up to more complex version incrementally. Install and try playing with `osc_modal_strike_16_nolimit` (16 refers to the number of filters in the resonator - nolimit means no dynamic limiter), `osc_modal_strike_24_nolimit` and finally `osc_modal_strike` (which has 24 filters and a dynamic limiter). It's important you use the same oscillator slot and don't reboot or install any other oscillators in between.

You may also want to try `osc_string` which is the Plaits version of the modal oscillator.

Let me know what you find!

Peace,

Peter

**Comment by cosmospacemonkey** [comment]
Awesome! Thanks for the new info and string osc. Will try the incremental installation of modal strike. I’ll let you know how it goes.

**Comment by NipLars** [comment]
Incredible cool new features on all oscillators - thank you.
My slots are full, bought some too - so will see if I remove any osc in future and test modal strike again.
In Prologue we have VPM as well so might be overlap somewhere.

Also concerned about cpu mentioned - since multi engine is running all the time - if any malfunction in synth might be possible. If not using on certain programs I try to have VPM chosen, since there is only volume - not any on/off.

**Comment by cosmospacemonkey** [comment]
Awesome! Thanks! Will try the incremental upload of Modal S. Will let you know :)

**Comment by eriklaurikulo** [comment]
I updated according to your instructions and it worked flawlessly. Thank you so much!

**Comment by peterall** [comment]
Thanks for checking it out guys! 😄

Let me know if the installation workaround doesn’t work for any of you and I’ll reopen the issue! 👍🏻

**Comment by cosmospacemonkey** [comment]
Worked perfectly! Both the string and Mod Strike is great for what i am doing :) Thanks!

**Comment by Sebo1971** [comment]
Hi Peter, modal oscillator is working well now! For some reason I think I like the "16 no limit" version more than the full version... but both works great. Thank you!!!

**Comment by PatrickECleary** [comment]
Modal Resonator isn't working on my NTS-1. I tried the proposed workaround of sequentially loading lower-CPU versions into the same slot, to no avail.

All the rest of the patches (based on Plaits) work splendidly though 😎 

As a newbie to the Korg synth line, maybe I missed something... does the NTS-1 have enough CPU power to handle the Modal Resonator patch?

**Comment by cosmospacemonkey** [comment]
Hi Peter,

Installed the eurorack into korg Minilogue XD - not getting any targets past 4. According to readme file, I should be able to see Lfo rate target, pitch, etc. all I have are three - parameter 1, parameter two, and target...and that only goes up to 4. Am I missing something? 

Thanks for any info :)
