### ISSUE TITLE
KORG NUTEKT NTS-1

### ISSUE THREAD

**Issue by cbmainz** [peterall/macro-oscillator2-prologue#3]
Will this support also the upcoming KORG NUTEKT NTS-1? Would be great if it would.

Thanks for sharing this project.

**Comment by peterall** [comment]
Hey! Yeah should definitely be doable, although I won’t be able to test it until December according to what the dealers in Sweden tell me! I’ll try to put some effort in within a few weeks.

Any delivery estimates where you’re at?

Tanks for the interest :)

**Comment by peterall** [comment]
Check out version 1.5 with untested builds for the NTS-1! 👍

**Comment by gilbertohasnofb** [comment]
@peterall did you have the chance to test them yet? I loaded all the Plaits-based oscillators on my NTS-1 but they sound very strange and buggy.

edit: so I just wonder if this is an issue just on my side or not.

**Comment by boochow** [comment]
> @peterall did you have the chance to test them yet? I loaded all the Plaits-based oscillators on my NTS-1 but they sound very strange and buggy.

@gilbertohasnofb I posted a PR [#6](https://github.com/peterall/eurorack-prologue/pull/6) for this issue.
You can download prebuilt binaries I made with the PR from:
http://blog.boochow.com/wp-content/uploads/eurorack_nutekt-digital.zip

**Comment by gilbertohasnofb** [comment]
@boochow Thank you so much for those builds, they work absolutely fine on my NTS-1. Many thanks!

**Comment by peterall** [comment]
@boochow Hey very cool, thanks for contributing, I'll check it out when I get a chance! And thanks @gilbertohasnofb for testing :)
