### ISSUE TITLE
Wavetable Oscillators Row and Colummn messed up.

### ISSUE THREAD

**Issue by Sebo1971** [peterall/macro-oscillator2-prologue#4]
Hi Peter:
First of all thank you for porting this oscillators to Prologue, they are great!
I found that there is somenthing wrong with the Row and Column selection and how the waves are selected in the Wavetable Oscillators (mo2_wta to mo2_wtf).
In the documentation you say there are 6 oscillators with 4 rows each, and I asume that there are 8 columns in each row. And you say that Shape selects the Row and Shift+Shap selects the Column.
But I can count 8 divisions (setting Interpolation to 2) when I turn Shape knob, so I think Shape meant to control Column instead of Row.
And I can count 5 divisions when I turn Shift+Shape knob. I think that should be the Row selection but I don't know why there are 5 Rows instead of 4...
The inverted nomenclature is not big problem, but according to the Braids manual within a row, the waves are sorted by spectral brightness, so there is some correlation in the order of the waves within a row and I expect that scaning the waves within a row using Shape the output will be correlated waves wich increases in harmonic content. Instead of that there are 3 or 4 waves correlated and the rest are mixed from other rows, and if I change rows I can found the waves that supposedly belong to other rows.
I don't have a Plaits module to check all this, but I tried it in the VCV Rack version (which is free) and confirmed that the wave order within a row is different in the mo2_wtx .
I think that you planed to assign Shape to Row and Shift-Shape to Column as stated in your documentation but at some point changed the amount of waves per turn of the knobs (because is more logical to have more divisions/waves in Shape knob) but didn't changed the assignment of the knob...
Hope you understand what I mean...

**Comment by peterall** [comment]
Hey! Thanks for finding this, I hadn't used the wavetable oscillator much but now when I dug into it it was all messed up - but I think I fixed it in 1.6! Thanks for the tip of validating with VCV Rack - ran though them and they seemed to produce the right result at least on Nu:tekt digital.

**Comment by Sebo1971** [comment]
Hi Peter! Yes the wave order is fixed in 1.6
Thank You!!! Great work!!!
Just one thing: In version 1.6 the Interpolate parameter is inverted. In previous versions, 1 was interpolated and 2 was non-interpolated. In this version, 1 is non-interpolated and 2 is interpolated. Can you change it to way there was? So I don't have to modify the presets I made... Thanks!!

**Comment by peterall** [comment]
Oh, sorry didn't mean to do that! There's a new 1.6.1 up now!

**Comment by Sebo1971** [comment]
Thank you very much!!!
