### ISSUE TITLE
Loaded the oscillators, killed a voice

### ISSUE THREAD

**Issue by NewBoio** [peterall/macro-oscillator2-prologue#5]
Tried loading all the oscillators onto my 3-week old minilogue xd – that had basically no problems prior – and immediately every fourth note i played in poly mode didn't make a sound. I don't know if i just got a bad unit, but it was working fine until i loaded the oscillators.

**Comment by peterall** [comment]
Hey, sorry to hear that - hope Korg was able to fix it for you 😞
