### ISSUE TITLE
Interpolate reversed

### ISSUE THREAD

**Issue by john-k-walton** [peterall/macro-oscillator2-prologue#7]
Hi Peter! Welcome back!

Thanks for fixing up R&C on wta-f. Please change this line:
parameters.harmonics = p_values[k_user_osc_param_id1] == 0 ? 1.f : 0.f;
To this
parameters.harmonics = p_values[k_user_osc_param_id1] == 0 ? 0.f : 1.f;

That will reverse the sense of Interpolate back the way it was, and still keep wavetables straightened out.

**Comment by peterall** [comment]
Sorry my bad, fixed it in 1.6.1! Thanks for finding it 👍

**Comment by john-k-walton** [comment]
Lol! No problem! I looked at that line several times a couple of months ago and couldn't figure out the constants. I thought once I spent more time on it, it would make sense. Guess not! :-)

These are really lovely models. Thank you for doing the port work. I've been playing with them exclusively since I got the compile platform setup earlier this year, to do my own development.

One thing I would like to see on your LFO2 version is a triangle wave instead of the stmlib cosine. The triangle wave has a more linear modulation rate. What do you think?

Thank you!
John
